# Generated by Django 4.1.7 on 2023-04-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdapp', '0004_feedback_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cartitem_table',
            },
        ),
    ]
