# Generated by Django 4.1.7 on 2023-04-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdapp', '0005_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'cart_table',
            },
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
