# Generated by Django 4.1.7 on 2023-04-02 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spdapp', '0006_cartproduct_delete_cartitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cartProduct',
        ),
    ]
