# Generated by Django 4.1.7 on 2023-05-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spdapp', '0012_customer_remove_cartitem_product_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product_table',
        ),
    ]
