# Generated by Django 4.1.7 on 2023-05-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spdapp', '0013_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='products_table',
        ),
    ]
