# Generated by Django 4.1.7 on 2023-05-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spdapp', '0014_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='registration',
            table='registrations_table',
        ),
    ]
