# Generated by Django 4.1.7 on 2023-05-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spdapp', '0016_alter_product_table_alter_registration_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customers_table',
        ),
    ]
