# Generated by Django 4.1.7 on 2023-05-07 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spdapp', '0018_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
